#!/usr/bin/python
import sys
import os

if len(sys.argv) != 2:
        print "Usage: gcc-config -L"
	sys.exit(1)

if sys.argv[1] == '-L':
        os.system('dirname `gcc -print-libgcc-file-name`')
else:
        raise "Unknown gcc-config option: " + sys.argv[1]

