#!/bin/sh
_xx=$1
x=$2
shift
shift
if [[ "$_xx" != '-o' ]]
then
	echo "ERROR: THE FIRST PARAMETERS TO $0 MUST BE -o outputfile"
	exit 1
fi

ld -T exe.ld -o $x lib/crt0start.o $*
echo ld -T exe.ld -o $x lib/crt0start.o $*

objcopy -I binary "$x" -O elf32-i386 "${x}.o"
echo objcopy -I binary "$x" -O elf32-i386 "${x}.o"
