#!/bin/bash
_xx=$1
x=$2
shift
shift
if [[ "$_xx" != '-o' ]]
then
	echo "ERROR: THE FIRST PARAMETERS TO $0 MUST BE -o outputfile"
	exit 1
fi

i586-pc-zsos-ld -o $x $* ./libpython2.5.a /opt/zsos-gcc/i586-pc-zsos/lib/libfakesys.o -T exe.ld
echo i586-pc-zsos-ld -o $x $* ./libpython2.5.a -T exe.ld 

i586-pc-zsos-objcopy -I binary "$x" -O elf32-i386 "${x}.o"
echo i586-pc-zsos-objcopy -I binary "$x" -O elf32-i386 "${x}.o"
